---
#
# Certificate handling, base procedures
#
# Copyright (C) 2025 The Tor Project, Inc.
# SPDX-License-Identifier: AGPL-3.0-or-later
#

- name: certs | base | Certificate configuration
  tags:
    - certificates
  block:
    - name: certs | base | Check if CA certificate file exists
      ansible.builtin.stat:
        path: "{{ onionspray_project.ca_file | default('/etc/ssl/certs/ca-certificates.crt') }}"
      register: onionspray_ca_file
      when: onionspray_project.check_cert_with_ca_file | default(true)

    - name: certs | base | Abort if CA certificate file is absent
      ansible.builtin.fail:
        msg: |
          No file present at path '{{ onionspray_project.ca_file }}'.
          This file should contain the CA certificate(s) used to check if the TLS certificate of the proxied domain is valid.
          On Debian-like systems, you can install the 'ca-certificates' package to create the CA file used by default.
          Otherwise, change the 'onionspray_ca_file' variable to the path of CA certificate(s) you want to use.
          You can also disable this check (not recommended) by setting 'onionspray_check_cert_with_ca_file' to 'false'.
      when:
        - onionspray_project.check_cert_with_ca_file | default(true)
        - not onionspray_ca_file.stat.exists

    - name: certs | base | Generate self-signed certificate configuration
      ansible.builtin.template:
        src   : certs/onionspray-certs.conf.j2
        dest  : "{{ onionspray_path }}/onionspray-certs.conf"
        owner : "{{ onionspray_user }}"
        group : "{{ onionspray_group }}"
        mode  : "644"
      #notify:
      #  - Remove Onionspray generated settings config files
      #  - Remove Onionspray generated project directories
      #  - Generate Onionspray configs
      #  - Restart Onionspray

    - name: certs | base | Create the project certs folder
      ansible.builtin.file:
        path    : "{{ onionspray_path }}/projects/{{ onionspray_project.name }}/ssl"
        owner   : "{{ onionspray_user }}"
        group   : "{{ onionspray_group }}"
        state   : directory
        mode    : '0700'
        recurse : false
