---
#
# Certificate copy
#
# Copyright (C) 2025 The Tor Project, Inc.
# SPDX-License-Identifier: AGPL-3.0-or-later
#

- name: "certs | copy | Copy Onion Service certificates for {{ onionspray_project_mapping }}"
  tags:
    - certificates
  when:
    - onionspray_project[onionspray_project_mapping] is defined
  block:
    - name: "certs | copy | Copy Onion TLS certificate for {{ onionspray_project_mapping }}"
      ansible.builtin.copy:
        content: "{{ onionspray_site.tls.certificate }}"
        dest: "{{ onionspray_path }}/projects/{{ onionspray_project.name }}/ssl/{ onionspray_site.onion_address | truncate(20, True, '')-v3.cert"
        owner: "{{ onionspray_user }}"
        group: "{{ onionspray_group }}"
        mode: "600"
      no_log: true
      loop: "{{ onionspray_project[onionspray_project_mapping] }}"
      loop_control:
        loop_var: onionspray_site
        label: onionspray_site.onion_address
      when:
        - onionspray_site.tls.certificate is defined
        - onionspray_site.tls.secret_key is defined
        - onionspray_site.onion_address is defined

    - name: "certs | copy | Copy Onion TLS secret key for {{ onionspray_project_mapping }}"
      ansible.builtin.copy:
        content: "{{ onionspray_site.tls.secret_key }}"
        dest: "{{ onionspray_path }}/projects/{{ onionspray_project.name }}/ssl/{ onionspray_site.onion_address | truncate(20, True, '')-v3.pem"
        owner: "{{ onionspray_user }}"
        group: "{{ onionspray_group }}"
        mode: "600"
      no_log: true
      loop: "{{ onionspray_project[onionspray_project_mapping] }}"
      loop_control:
        loop_var: onionspray_site
        label: onionspray_site.onion_address
      when:
        - onionspray_site.tls.certificate is defined
        - onionspray_site.tls.secret_key is defined
        - onionspray_site.onion_address is defined
