---
#
# GitLab CI for Ansible roles
#
# Copyright (C) 2024 The Tor Project, Inc.
# SPDX-License-Identifier: AGPL-3.0-or-later
#

# Variables
variables:
  ROLE: onionspray

# Templates
include:
  # AnCIble
  - project: tpo/onion-services/ansible/ancible
    file:
      - .gitlab-ci-base.yml

  # GitLab releases
  - project: tpo/onion-services/ci-templates
    file: onion-services/release.yml

# Linting
lint:
  extends: .ancible_lint

# Testing with Molecule and Podman
molecule_podman:
  extends: .ancible_molecule_podman

# Releases
release:
  !reference [.release-gitlab]
