---
#
# GitLab CI for Ansible roles
#
# Copyright (C) 2024 The Tor Project, Inc.
# SPDX-License-Identifier: AGPL-3.0-or-later
#

# Variables
variables:
  ROLE: onionspray

include:
  - project: tpo/onion-services/ansible/ancible
    file:
      - .gitlab-ci-base.yml

lint:
  extends: .ancible_lint

molecule_podman:
  extends: .ancible_molecule_podman

release:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  stage: .post
  rules:
    # Run this job when a tag is created
    - if: $CI_COMMIT_TAG
  script:
    - echo "Running release_job..."
  release:
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'
