---
#
# GitLab CI for Ansible roles
#
# Copyright (C) 2024 The Tor Project, Inc.
# SPDX-License-Identifier: AGPL-3.0-or-later
#

# Variables
variables:
  ROLE: onionspray

include:
  - project: tpo/onion-services/ansible/ancible
    file:
      - .gitlab-ci-base.yml

lint:
  extends: .ancible_lint

molecule_podman:
  extends: .ancible_molecule_podman
