---
#
# Builds Onionspray
#
# Copyright (C) 2024 The Tor Project, Inc.
# SPDX-License-Identifier: AGPL-3.0-or-later
#

- name: build | Check Onionspray build status
  block:
    - name: build | Check if Onionspray has already been built
      ansible.builtin.stat:
        dest: "{{ onionspray_path }}/.onionspray-build-info/{{ onionspray_platform }}"
      register: onionspray_check_has_been_built

- name: build | Handle Onionspray dependencies
  block:
    - name: build | Install Onionspray build dependencies
      ansible.builtin.command:
        cmd: "{{ onionspray_path }}/opt/{{ onionspray_deps_script }} | tee {{ onionspray_path }}/log/deps-{{ ansible_date_time.epoch }}.log"
      become: true
      changed_when: true
      when:
        - not onionspray_check_has_been_built.stat.exists

- name: build | Handle Onionspray build
  block:
    # This file was used to indicate whether Onionspray has already been built or not
    # No longer needed, since Onionspray now have build metadata available:
    # https://gitlab.torproject.org/tpo/onion-services/onionspray/-/merge_requests/114
    - name: build | Remove the legacy build lock file
      ansible.builtin.file:
        path: "{{ onionspray_build_lock_file | default('{{ onionspray_path }}/onionspray-already-built.lock') }}"
        state: absent

    - name: build | Build Onionspray
      ansible.builtin.command:
        cmd: "{{ onionspray_path }}/opt/{{ onionspray_compile_script }} | tee {{ onionspray_path }}/log/compile-{{ ansible_date_time.epoch }}.log"
      become: true
      become_user: "{{ onionspray_user }}"
      # Workaround allowing to run Git even if the shell is set to /sbin/nologin
      # Discussed at https://stackoverflow.com/questions/50512402/can-ansible-use-sudo-su-if-the-sudo-user-is-not-allowed-to-run-arbitrary-scr
      # Alternative: https://docs.ansible.com/ansible/latest/collections/community/general/sudosu_become.html
      become_method: "ansible.builtin.sudo"
      become_flags: "su -s /bin/bash - {{ onionspray_user }} /bin/bash -c"
      changed_when: true
      when:
        - not onionspray_check_has_been_built.stat.exists
