---
#
# Onionspray role
#
# Copyright (C) 2024 The Tor Project, Inc.
# SPDX-License-Identifier: AGPL-3.0-or-later
#

- name: User handling
  ansible.builtin.include_tasks: user.yml

- name: Repository management
  ansible.builtin.include_tasks: repo.yml

- name: Key handling
  ansible.builtin.include_tasks: keys.yml

- name: Certificate handling
  ansible.builtin.include_tasks: certs.yml
  loop: "{{ onionspray_project_settings }}"
  loop_control:
    loop_var: settings
    label: settings.project_name

- name: Projects configuration
  ansible.builtin.include_tasks: projects.yml
  loop: "{{ onionspray_project_settings }}"
  loop_control:
    loop_var: settings
    label: settings.project_name

- name: Build
  ansible.builtin.include_tasks: build.yml

- name: Service setup
  ansible.builtin.include_tasks: service.yml
