---
#
# Projects configuration
#
# Copyright (C) 2024 The Tor Project, Inc.
# SPDX-License-Identifier: AGPL-3.0-or-later
#

- name: "projects | Generate project settings for {{ onionspray_project.name }}"
  ansible.builtin.template:
    src: projects/project.tconf.j2
    dest: "{{ onionspray_path }}/{{ onionspray_project.name }}.tconf"
    owner: "{{ onionspray_user }}"
    group: "{{ onionspray_user }}"
    mode: "600"
  notify:
    - Remove Onionspray generated settings config files
    # The following is commented as might remove existing logs
    #- Remove Onionspray generated project directories
    - Generate Onionspray configs
    - Configure Onionspray projects
    - Restart Onionspray
