---
#
# Key copying
#
# Copyright (C) 2025 The Tor Project, Inc.
# SPDX-License-Identifier: AGPL-3.0-or-later
#

- name: "keys | copy | Copy Onion Service keys for {{ onionspray_project_mapping }}"
  tags:
    - keys
  when:
    - onionspray_project[onionspray_project_mapping] is defined
  block:
    - name: "keys | copy | Copy Onion v3 public key for {{ onionspray_project_mapping }}"
      ansible.builtin.copy:
        content: "{{ onionspray_site.public_key_base64 | b64decode }}"
        dest: "{{ onionspray_path }}/secrets/{{ onionspray_site.onion_address }}.v3pub.key"
        owner: "{{ onionspray_user }}"
        group: "{{ onionspray_user }}"
        mode: "600"
      no_log: true
      loop: "{{ onionspray_project[onionspray_project_mapping] }}"
      loop_control:
        loop_var: onionspray_site
        label: onionspray_site.onion_address
      when:
        - onionspray_site.public_key_base64 is defined
        - onionspray_site.secret_key_base64 is defined
        - onionspray_site.onion_address is defined

    - name: "keys | copy | Copy Onion v3 secret key for {{ onionspray_project_mapping }}"
      ansible.builtin.copy:
        content: "{{ onionspray_site.secret_key_base64 | b64decode }}"
        dest: "{{ onionspray_path }}/secrets/{{ onionspray_site.onion_address }}.v3sec.key"
        owner: "{{ onionspray_user }}"
        group: "{{ onionspray_user }}"
        mode: "600"
      no_log: true
      loop: "{{ onionspray_project[onionspray_project_mapping] }}"
      loop_control:
        loop_var: onionspray_site
        label: onionspray_site.onion_address
      when:
        - onionspray_site.public_key_base64 is defined
        - onionspray_site.secret_key_base64 is defined
        - onionspray_site.onion_address is defined
