---
#
# Key handling
#
# Copyright (C) 2024 The Tor Project, Inc.
# SPDX-License-Identifier: AGPL-3.0-or-later
#

- name: keys | Create secrets directory
  ansible.builtin.file:
    path: "{{ onionspray_repo_download_path }}/secrets/"
    state: directory
    owner: "{{ onionspray_user }}"
    group: "{{ onionspray_user }}"
    mode: "700"

- name: keys | Copy Onion Service keys
  ansible.builtin.include_tasks: keys/copy.yml
  loop: [ 'hardmaps', 'softmaps' ]
  loop_control:
    loop_var: mapping
