---
#
# Key handling
#
# Copyright (C) 2025 The Tor Project, Inc.
# SPDX-License-Identifier: AGPL-3.0-or-later
#

- name: "keys | main | Base keys configuration for {{ onionspray_project_settings.project_name }}"
  ansible.builtin.include_tasks: keys/base.yml

- name: "keys | main | Copy Onion Service keys for {{ onionspray_project_settings.project_name }}"
  ansible.builtin.include_tasks: keys/copy.yml
  no_log: true
  loop: ['hardmaps', 'softmaps']
  loop_control:
    loop_var: onionspray_project_mapping

- name: "keys | main | Upload Onion Service keys for {{ onionspray_project_settings.project_name }}"
  ansible.builtin.include_tasks: keys/upload.yml
  no_log: true
  loop: ['hardmaps', 'softmaps']
  loop_control:
    loop_var: onionspray_project_mapping
