---
#
# Keys upload
#
# Copyright (C) 2025 The Tor Project, Inc.
# SPDX-License-Identifier: AGPL-3.0-or-later
#

- name: "keys | upload | Upload Onion Service keys for {{ onionspray_project_mapping }}"
  tags:
    - keys
  when:
    - onionspray_project[onionspray_project_mapping] is defined
  block:
    - name: "Debug onionspray key uploader command line invocation for {{ onionspray_project_mapping }}"
      ansible.builtin.debug:
        msg: >
          {{ onionspray_key_uploader_script }} {{ onionspray_provider }} {{ inventory_hostname }}
          {{ onionspray_project.name }} {{ onionspray_site.onion_address }} {{ onionspray_site.upstream_address }}
          {{ onionspray_user }}
          {{ onionspray_path }}
      loop         : "{{ onionspray_project[onionspray_project_mapping] }}"
      loop_control :
        loop_var : onionspray_site
        label    : "{{ onionspray_site.onion_address }}"
      when:
        - onionspray_debug
        - onionspray_site.onion_address is defined
        - onionspray_site.keys_upload is defined
        - onionspray_site.keys_upload == true
        - onionspray_key_uploader_script | length != 0

    #- name: "Ensure the public key file existence and permissions for {{ onionspray_project_mapping }}"
    #  ansible.builtin.file:
    #    path  : "{{ onionspray_path }}/projects/{{ onionspray_project.name }}/{{ onionspray_site.onion_address }}-v3pub.key"
    #    owner : "{{ onionspray_user }}"
    #    group : "{{ onionspray_user }}"
    #    state : touch
    #    mode  : '0600'
    #  loop_control:
    #    loop_var : onionspray_site
    #    label    : "{{ onionspray_site.onion_address }}"
    #  when:
    #    - onionspray_site.onion_address is defined
    #    - onionspray_site.keys_upload is defined
    #    - onionspray_site.keys_upload == true
    #    - onionspray_key_uploader_script | length != 0

    #- name: "Ensure the private key file existence and permissions for {{ onionspray_project_mapping }}"
    #  ansible.builtin.file:
    #    path  : "{{ onionspray_path }}/projects/{{ onionspray_project.name }}/{{ onionspray_site.onion_address }}-v3sec.key"
    #    owner : "{{ onionspray_user }}"
    #    group : "{{ onionspray_user }}"
    #    state : touch
    #    mode  : '0600'
    #  loop_control:
    #    loop_var : onionspray_site
    #    label    : "{{ onionspray_site.onion_address }}"
    #  when:
    #    - onionspray_site.onion_address is defined
    #    - onionspray_site.keys_upload is defined
    #    - onionspray_site.keys_upload == true
    #    - onionspray_key_uploader_script | length != 0

    - name: "keys | upload | Upload Onion Service keys for {{ onionspray_project_mapping }}"
      ansible.builtin.command:
        cmd: >
          {{ onionspray_key_uploader_script }} {{ onionspray_provider }} {{ inventory_hostname }}
          {{ onionspray_project.name }} {{ onionspray_site.onion_address }} {{ onionspray_site.upstream_address }}
          {{ onionspray_user }}
          {{ onionspray_path }}
          {{ onionspray_keyring }}
          {{ onionspray_secrets_manager }}
      delegate_to : localhost
      connection  : local
      become      : true
      become_user : "{{ lookup('env', 'USER') }}"
      loop        : "{{ onionspray_project[onionspray_project_mapping] }}"
      loop_control:
        loop_var : onionspray_site
        #label   : "{{ onionspray_site.onion_address }}"
      when:
        - onionspray_site.onion_address is defined
        - onionspray_site.keys_upload is defined
        - onionspray_site.keys_upload
        - onionspray_key_uploader_script | length != 0
      notify : Restart Onionspray

      # This task always change something (even if only the mtime of a file)
      changed_when: true

      # Under normal circumstances, this is equivalent to "changed_when: true", with the difference
      # that may pass idempotence tests
      #register: onionspray_upload_keys_hardmaps
      #changed_when: onionspray_upload_keys_harmaps.rc != 0
