---
#
# Onionspray Ansible role test playbook
#
# Copyright (C) 2024 The Tor Project, Inc.
# SPDX-License-Identifier: AGPL-3.0-or-later
#

- name: Converge
  hosts: all

  # Gathering facts requires a container with Python installed
  gather_facts: true

  vars:
    onionspray_project_settings:
      - project_name: "example1"
        softmaps:
          - upstream_address: example.com
          - upstream_address: example.org
      - project_name: "example2"
        hardmaps:
          # Bogus data for testing purposes
          - onion_address: yetkvkuqlr23sdzkf2mynt7aixfjzq6pjys2ffurr3hzpyfxrc7swpqd
            upstream_address: example.net
            public_key_base64: Ym9ndXMgZGF0YSBmb3IgdGVzdGluZyBwdXJwb3Nlcwo=
            secret_key_base64: Ym9ndXMgZGF0YSBmb3IgdGVzdGluZyBwdXJwb3Nlcwo=
            tls_certificate: |
              TLS_CERTIFICATE
            tls_secret_key: |
              TLS_SECRET_KEY_ENCRYPTED_WITH_ANSIBLE_VAULT
        foreingmaps:
          - onion_address: exaymhwjhgdopeebkv5p3lmb5vu2mmvcc7krpgwx6ngf4uvob2whkcqd.onion
            upstream_address: example.info
        log_separate                 : '1'
        nginx_resolver               : '127.0.0.53 ipv6=off'
        nginx_cache_seconds          : '60'
        nginx_cache_size             : '64m'
        nginx_tmpfile_size           : '8m'
        x_from_onion_value           : '1'
        tor_export_circuit_id        : 'haproxy'
        tor_intros_per_daemon        : '6'
        tor_single_onion             : '1'
        tor_pow_enabled              : '1'
        tor_max_streams              : '5000'
        tor_max_streams_close_circuit: '1'
        tor_intro_dos_defense        : '1'
        tor_intro_dos_burst_per_sec  : '20000'
        tor_intro_dos_rate_per_sec   : '20000'
        custom_settings: |
          # block access to "forbidden" subdomain
          set block_err This subdomain is forbidden.
          set block_host_re ^forbidden\.

        # Test S3 log upload to the test MinIO instance
        #
        # Don't use these values in production systems!
        #
        # Details at
        # https://docs.min.io/community/minio-object-store/integrations/aws-cli-with-minio.html
        log_s3_upload                : true
        log_s3_upload_api_endpoint   : 'https://play.min.io:9000'
        log_s3_access_key_id         : 'Q3AM3UQ867SPQQA43P2F'
        log_s3_access_key            : 'zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG'

    # Do not enable the service, since the image is not started with systemd as PID 1
    onionspray_use_systemd: false

    # Deploy logic for managing the service through cron
    onionspray_use_crond: true

    # Deploy logic for aperiodic restarts
    onionspray_aperiodic_restarts: true

  pre_tasks:
    - name: Run pre-tasks
      ansible.builtin.include_tasks: tasks/deps.yml

  roles:
    - onionspray
