---
#
# Onionspray Ansible molecule test
#
# Copyright (C) 2025 The Tor Project, Inc.
# SPDX-License-Identifier: AGPL-3.0-or-later
#

dependency:
  name: galaxy
  options:
    requirements-file: requirements-podman.yml

driver:
  name: podman
  options:
    managed: false
    login_cmd_template: "podman exec -ti {instance} bash"
    ansible_connection_options:
      ansible_connection: podman

platforms:
  - name: all
    # Use a container with Python pre-installed
    image           : docker.io/python:trixie
    pre_build_image : true
    privileged      : true

    # Container entrypoint
    # A command that keeps the container running
    command: ${MOLECULE_DOCKER_COMMAND:-"sleep infinity"}

    extra_opts:
      # May fix "Error: crun: sethostname: Operation not permitted: OCI permission denied"
      # https://github.com/containers/podman/issues/14284#issuecomment-1130113553
      #- --group-add=keep-groups

      # May fix "sethostname: Operation not permitted: OCI permission denied"
      # Details at https://github.com/containers/podman/discussions/25061
      #- --cap-add=SYS_ADMIN

      # Debug output
      - --log-level=debug
