---
#
# Onionspray Ansible molecule test
#
# Copyright (C) 2024 The Tor Project, Inc.
# SPDX-License-Identifier: AGPL-3.0-or-later
#

dependency:
  name: galaxy
  options:
    requirements-file: requirements-podman.yml

driver:
  name: podman
  options:
    managed: false
    login_cmd_template: "podman exec -ti {instance} bash"
    ansible_connection_options:
      ansible_connection: podman

platforms:
  - name: all
    # Use a container with Python pre-installed
    image           : docker.io/python:bookworm
    pre_build_image : true
    privileged      : true

    # Container entrypoint
    # A command that keeps the container running
    command: ${MOLECULE_DOCKER_COMMAND:-"sleep infinity"}
