#!/usr/bin/env bash
#
# Helper script to setup a development environment
#
# Copyright (C) 2024 The Tor Project, Inc.
# SPDX-License-Identifier: AGPL-3.0-or-later
#

# Parameters
DIRNAME="`dirname $0`"
BASEPATH="$DIRNAME/.."
DEPENDENCIES_APT="podman podman-compose python3-pip ansible make"
DEPENDENCIES_PIP="molecule-plugins[podman] ansible-lint"

# Check for sudo
if [ "`whoami`" != "root" ]; then
  SUDO="sudo"
fi

# System upgrade
$SUDO apt-get update
$SUDO apt-get upgrade -y

# Install dependencies
$SUDO apt install -y $DEPENDENCIES_APT
$SUDO python3 -m pip install $DEPENDENCIES_PIP --break-system-packages

# Create a symlink so molecule and ansible-lint can find the role
for scenario in podman local; do
  if [ ! -e "$BASEPATH/molecule/$scenario/roles/onionspray" ]; then
    mkdir -p $BASEPATH/molecule/$scenario/roles && \
      ln -sf ../../.. $BASEPATH/molecule/$scenario/roles/onionspray
  fi
done
